### ISSUE TITLE
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM6

### ISSUE THREAD

**Issue by Neacy** [eleme/lancet#67]
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:130)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:724)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:544)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at me.ele.lancet.plugin.internal.preprocess.AsmClassProcessorImpl.process(AsmClassProcessorImpl.java:15)
	at me.ele.lancet.plugin.internal.preprocess.PreClassAnalysis$PreAnalysisClassFetcher.onClassFetch(PreClassAnalysis.java:127)
	at me.ele.lancet.plugin.internal.context.JarContentProvider.forActualInput(JarContentProvider.java:34)
	at me.ele.lancet.plugin.internal.context.JarContentProvider.forEach(JarContentProvider.java:22)
	at me.ele.lancet.plugin.internal.context.ClassifiedContentProvider.forEach(ClassifiedContentProvider.java:29)
	at me.ele.lancet.plugin.internal.context.ContextReader$QualifiedContentTask.call(ContextReader.java:131)
	at me.ele.lancet.plugin.internal.context.ContextReader$QualifiedContentTask.call(ContextReader.java:119)

**Comment by wangzhiwei8989** [comment]
你好，这个错误解决了吗，我引入也报这个错误

**Comment by chenyi2013** [comment]
> 你好，这个错误解决了吗，我引入也报这个错误

可以用这个https://github.com/DarkAdventurer93/lancet

**Comment by starlingever** [comment]
> > 你好，这个错误解决了吗，我引入也报这个错误
> 
> 可以用这个https://github.com/DarkAdventurer93/lancet

你好这个感觉还是不太行呀，提示找不到classpath 'com.github.HairySnow.lancet:lancet-plugin:1.0.3'
